const products=[
{id:1,slug:'magnolia-chembakam-shower-gel',name:'Magnolia & Chembakam Shower Gel',category:'Skin Care',price:449,image:'assets/products/Magnolia%20Chembakam%20Shower%20Gel%20with%20Hydrolyzed%20Silk%20Protein%20%26%20Vitamin%20E.jpg',description:'A floral botanical body cleanser designed for a soft, unhurried everyday ritual.'},
{id:2,slug:'neem-peppermint-shower-gel',name:'Neem & Peppermint Shower Gel',category:'Skin Care',price:399,image:'assets/products/Neem%20%26%20Peppermint%20Shower%20Gel.jpg',description:'A fresh, nature-inspired cleansing essential for your daily routine.'},
{id:3,slug:'onion-hibiscus-hair-gel',name:'Onion & Hibiscus Hair Gel',category:'Hair Care',price:349,image:'assets/products/Onion%20%26%20Hibiscus%20Hair%20Gel%20100gm.jpg',description:'A botanical-inspired styling care essential made for everyday hair rituals.'},
{id:4,slug:'rose-face-wash',name:'Rose Face Wash',category:'Skin Care',price:449,image:'assets/products/Rose%20Face%20Wash-%20Gentle%20Daily%20Cleanser%20with%20Organic%20Roses%2C%20Aloe%20Vera%2C%20Niacinamide%20and%20Rice%20Extract.jpg',description:'A gentle daily cleanser inspired by roses, aloe vera, niacinamide and rice extract.'},
{id:5,slug:'skin-bright-glow-oil',name:'Skin Bright Glow Oil',category:'Herbal Essentials',price:499,image:'assets/products/Skin%20Bright%20Glow%20Oil%20100ml%20%E2%80%93%20Kerala%20Ayurvedic%20Formula%20with%20Pure%20Ghee%2C%20Rice%20Extract%20%26%20Sesame%20Oil.jpg',description:'A Kerala Ayurvedic-inspired glow oil with pure ghee, rice extract and sesame oil.'}];
const q=s=>document.querySelector(s),fmt=n=>'₹'+n.toLocaleString('en-IN');let cart=JSON.parse(localStorage.getItem('maaz-cart')||'[]');
function img(p,c='product-image'){return `<img class="${c}" src="${p.image}" alt="${p.name}" loading="lazy">`}
function card(p){return `<article class="card"><button class="wish" aria-label="Add ${p.name} to wishlist">♡</button><a href="product.html?slug=${p.slug}" class="product-visual">${img(p)}</a><p class="eyebrow">${p.category}</p><h3>${p.name}</h3><p class="price">${fmt(p.price)} <small>✦ Botanical care</small></p><button class="add" data-add="${p.id}">Add to bag <span>+</span></button></article>`}
function save(){localStorage.setItem('maaz-cart',JSON.stringify(cart))}function add(id,qty=1){let p=products.find(x=>x.id===+id),x=cart.find(x=>x.id===p.id);x?x.qty+=qty:cart.push({...p,qty});save();renderCart();toast(`${p.name} added to your bag`)}
function renderCart(){let t=q('#cartItems');if(!t)return;let count=cart.reduce((n,x)=>n+x.qty,0),total=cart.reduce((n,x)=>n+x.qty*x.price,0);q('#navCount').textContent=count;q('#cartCount').textContent=`(${count})`;q('#subtotal').textContent=fmt(total);t.innerHTML=cart.length?cart.map(x=>`<div class="cart-item">${img(x)}<div><strong>${x.name}</strong><small>${fmt(x.price)}</small><div class="qty"><button data-qty="${x.id}" data-delta="-1">−</button><span>${x.qty}</span><button data-qty="${x.id}" data-delta="1">+</button><button class="remove" data-remove="${x.id}">Remove</button></div></div></div>`).join(''):'<div class="empty cart-empty"><strong>Your botanical basket is empty.</strong><p>Discover something naturally beautiful.</p></div>'}
function renderShop(){let grid=q('#allProducts');if(!grid)return;let s=(q('#shopSearch')?.value||'').toLowerCase(),c=q('#categoryFilter')?.value||'All Products',o=q('#sortFilter')?.value||'featured',list=products.filter(p=>(!s||(p.name+p.category).toLowerCase().includes(s))&&(c==='All Products'||p.category===c));if(o==='low')list.sort((a,b)=>a.price-b.price);if(o==='high')list.sort((a,b)=>b.price-a.price);if(o==='name')list.sort((a,b)=>a.name.localeCompare(b.name));grid.innerHTML=list.length?list.map(card).join(''):'<p class="empty">No botanical essentials found. Try another search.</p>';if(q('#productCount'))q('#productCount').textContent=`${list.length} products`}
function toast(m){let t=q('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}function toggle(id,on=true){q('#'+id)?.classList.toggle('open',on);q('#scrim')?.classList.toggle('open',on);document.body.classList.toggle('locked',on)}
function renderProduct(){let h=q('#productPage');if(!h)return;let p=products.find(x=>x.slug===new URLSearchParams(location.search).get('slug'))||products[0],related=products.filter(x=>x.id!==p.id).slice(0,3);document.title=`${p.name} — MAAZ Herbals`;h.innerHTML=`<section class="product-page section"><a class="text-button" href="shop.html">← Back to shop</a><div class="product-page-grid"><div class="page-image">${img(p)}</div><div class="page-copy"><p class="eyebrow">${p.category}</p><h1>${p.name}</h1><p class="detail-price">${fmt(p.price)} <small>★★★★★ · Botanical personal care</small></p><p>${p.description}</p><div class="detail-quantity"><span>Quantity</span><button id="minus">−</button><b id="quantity">1</b><button id="plus">+</button></div><button class="button dark" id="productAdd">Add to bag</button><button class="button buy" id="buyNow">Buy now</button><details open><summary>Product highlights</summary><p>Herbal-inspired, thoughtfully chosen for a simple everyday routine.</p></details><details><summary>Ingredients</summary><p>See the product pack for its complete and current ingredient list.</p></details><details><summary>How to use</summary><p>Use as part of your preferred personal-care routine. Patch test where appropriate.</p></details><details><summary>Shipping & returns</summary><p>Frontend demo — shipping details can be connected before production.</p></details></div></div></section><section class="section related"><p class="eyebrow">Continue your ritual</p><h2>You may also <em>like.</em></h2><div class="product-grid">${related.map(card).join('')}</div></section>`;let n=1;q('#plus').onclick=()=>q('#quantity').textContent=++n;q('#minus').onclick=()=>q('#quantity').textContent=Math.max(1,--n);q('#productAdd').onclick=()=>add(p.id,n);q('#buyNow').onclick=()=>{add(p.id,n);toggle('cart')}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-add]');if(b){e.preventDefault();add(b.dataset.add)}if(e.target.matches('[data-close]'))toggle(e.target.dataset.close,false);if(e.target.id==='scrim')toggle('cart',false);if(e.target.matches('[data-qty]')){let x=cart.find(x=>x.id===+e.target.dataset.qty);x.qty+=+e.target.dataset.delta;if(x.qty<1)cart=cart.filter(y=>y!==x);save();renderCart()}if(e.target.matches('[data-remove]')){cart=cart.filter(x=>x.id!==+e.target.dataset.remove);save();renderCart()}});
q('#openCart')?.addEventListener('click',()=>toggle('cart'));q('#openSearch')?.addEventListener('click',()=>toggle('searchPanel'));q('#checkout')?.addEventListener('click',()=>toast('This is a frontend demo. Checkout can be connected later.'));q('#mobileMenu')?.addEventListener('click',()=>q('.nav nav')?.classList.toggle('mobile-open'));q('#searchInput')?.addEventListener('input',e=>{let l=products.filter(p=>(p.name+p.category).toLowerCase().includes(e.target.value.toLowerCase()));q('#searchResults').innerHTML=l.map(p=>`<a href="product.html?slug=${p.slug}">${img(p)}<span>${p.name}<small>${p.category} · ${fmt(p.price)}</small></span></a>`).join('')||'<p class="empty">No botanical essentials found.</p>'});['#shopSearch','#categoryFilter','#sortFilter'].forEach(s=>q(s)?.addEventListener('input',renderShop));q('#newsletterForm')?.addEventListener('submit',e=>{e.preventDefault();q('#formMessage').textContent='Thank you — your ritual notes are on their way.';e.target.reset()});window.addEventListener('scroll',()=>q('#nav')?.classList.toggle('scrolled',scrollY>50));
if(q('#featuredProducts'))q('#featuredProducts').innerHTML=products.slice(0,4).map(card).join('');if(q('.hero-art img')){q('.hero-art').classList.add('campaign-hero');q('.hero-art img').src='assets/campaign/glow-oil-hero.png';q('.hero-art img').alt='MAAZ Herbals Skin Bright Glow Oil botanical campaign'}if(q('.feature-image img')){q('.feature-image img').src=products[0].image;q('.feature-image img').alt=products[0].name}const routes={Home:'index.html',Shop:'shop.html',Collections:'collections.html','Our Story':'story.html'};document.querySelectorAll('.nav nav a').forEach(a=>{if(routes[a.textContent.trim()])a.href=routes[a.textContent.trim()]});renderShop();renderCart();renderProduct();setTimeout(()=>q('#loader')?.classList.add('done'),1800);
